name = "aiken-lang/hello-world"
version = "0.0.0"
compiler = "v1.1.15"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/hello-world'"

[repository]
user = "aiken-lang"
project = "hello-world"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.1-beta"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2"
source = "github"

[config.default]
asset = [
    "HOSKY",
    42,
]
is_mainnet = true
network = "mainnet"
price = 1
quotas = [
    1,
    2,
    3,
]

[config.default.owner]
bytes = "0000111122223333"
encoding = "base16"
